export enum CategorieAnomalie {
  COMPTEUR = "COMPTEUR",
  ACCES = "ACCES",
  LECTURE = "LECTURE",
  INSTALLATION = "INSTALLATION",
  TECHNIQUE = "TECHNIQUE",
  ADMINISTRATIF = "ADMINISTRATIF",
  ENVIRONNEMENT = "ENVIRONNEMENT",
  AUTRE = "AUTRE"
}
