// types/typePhoto.ts
export enum TypePhoto {
  COMPTEUR_PRINCIPAL = "COMPTEUR_PRINCIPAL",
  COMPTEUR_DETAIL = "COMPTEUR_DETAIL",
  INDEX = "INDEX",
  ANOMALIE = "ANOMALIE",
  ENVIRONNEMENT = "ENVIRONNEMENT",
  INSTALLATION = "INSTALLATION",
  AVANT_INTERVENTION = "AVANT_INTERVENTION",
  APRES_INTERVENTION = "APRES_INTERVENTION",
  AUTRE = "AUTRE"
}
